apiVersion: skaffold/v2alpha3
kind: Config
deploy:
 kubectl :
  manifests :
   - ./infra/K8s/*
build:
 local:
  push: false
 artifacts:
    
    - image : kannans89/post
      context: posts
      docker :
       dockerfile: Dockerfile
      sync:
         manual:
          - src : '*.js'
            dest : .

    - image: kannans89/event-bus
      context: event-bus
      docker :
       dockerfile: Dockerfile
      sync:
       manual:
        - src : '*.js'
          dest : .

    - image: kannans89/comments
      context: comments
      docker :
        dockerfile: Dockerfile
      sync:
       manual:
        - src : '*.js'
          dest : .
    - image: kannans89/query
      context: query
      docker :
        dockerfile: Dockerfile
      sync:
       manual:
        - src : '*.js'
          dest : .
    - image: kannans89/client
      context: client
      docker :
          dockerfile: Dockerfile
      sync:
       manual:
        - src : 'src/**/*.js'
          dest : . 
