name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
         cluster_name: my-first-cluster-1
         location: asia-east1-a
     - run: kubectl apply -f infra/K8s && kubectl apply -f infra/K8s-prod
