name: deploy-comments

on:
  push:
    branches:
      - master
    paths:
      - 'comments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - run: cd comments && gcloud builds submit --tag us.gcr.io/decoded-plane-339211/comments
      - uses: google-github-actions/get-gke-credentials@v0
        with:
         cluster_name: my-first-cluster-1
         location: asia-east1-a
      - run: kubectl rollout restart deployment comments-depl

